name    'bazzie-beaver'
version '0.0.1'
source 'https://github.com/bazzie/puppet-beaver.git'
author 'Bas Wildemann'
license 'Apache License, Version 2.0'
summary 'Module for managing and configuring beaver'
description 'Module for managing and configuring beaver'
project_page 'https://github.com/bazzie/puppet-beaver.git'
dependency 'puppetlabs/stdlib', '>= 3.0.0'
dependency 'ispavailability/file_concat', '>= 0.0.1'
dependency 'footballradar/python', '0.x'
